# Пользователь
@hostname = http://localhost
@port = 3333
@prefix = api/v1
@host = {{hostname}}:{{port}}/{{prefix}}
@parentPath = auth
@contentType = application/json
# @USER_ID = 65a8be2bf72eba2b50420cf7
@USER_ID = 1



### Регистрация пользователя
POST {{host}}/{{parentPath}}/register HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "2@2.net",
  "firstname": "Jay",
  "password": "shining"
}

###

## Авторизовать пользователя

POST {{host}}/{{parentPath}}/login HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "2@2.net",
  "password": "shining"
}

###
## Проверка пользователя

GET {{host}}/{{parentPath}}/{{USER_ID}} HTTP/1.1


###
## Изменение пароля пользователя
PATCH {{host}}/{{parentPath}}/change-password/{{USER_ID}} HTTP/1.1
Content-Type: {{contentType}}

{  
  "oldPassword": "shining3",
  "newPassword": "shining2"
}

###